GET / HTTP/1.1
Accept: 0
Accept: 1
Accept: 2
Accept: 3
Accept: 4
Accept: 5
Accept: 6
Accept: 7
Accept: 8
Accept: 9
Accept: 10
Accept: 11
Accept: 12
Accept: 13
Accept: 14
Accept: 15
Accept: 16
Accept: 17
Accept: 18
Accept: 19
Accept: 20
Accept: 21
Accept: 22
Accept: 23
Accept: 24
Accept: 25
Accept: 26
Accept: 27
Accept: 28
Accept: 29
Accept: 30
Accept: 31
Accept: 32
Accept: 33
Accept: 34
Accept: 35
Accept: 36
Accept: 37
Accept: 38
Accept: 39
Accept: 40
Accept: 41
Accept: 42
Accept: 43
Accept: 44
Accept: 45
Accept: 46
Accept: 47
Accept: 48
Accept: 49
Accept: 50
Accept: 51
Accept: 52
Accept: 53
Accept: 54
Accept: 55
Accept: 56
Accept: 57
Accept: 58
Accept: 59
Accept: 60
Accept: 61
Accept: 62
Accept: 63
Accept: 64
Accept: 65
Accept: 66
Accept: 67
Accept: 68
Accept: 69
Accept: 70
Accept: 71
Accept: 72
Accept: 73
Accept: 74
Accept: 75
Accept: 76
Accept: 77
Accept: 78
Accept: 79
Accept: 80
Accept: 81
Accept: 82
Accept: 83
Accept: 84
Accept: 85
Accept: 86
Accept: 87
Accept: 88
Accept: 89
Accept: 90
Accept: 91
Accept: 92
Accept: 93
Accept: 94
Accept: 95
Accept: 96
Accept: 97
Accept: 98
Accept: 99

